# Generated by Django 5.1.7 on 2025-03-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='reason_entry',
            new_name='reason_entry1',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='reason_exit',
            new_name='reason_exit1',
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_entry2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_exit2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
