# Generated by Django 5.1.7 on 2025-03-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_reason_entry_trade_reason_entry1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='reason_entry2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_exit2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
