# Generated by Django 5.1.7 on 2025-03-23 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trade_reason_entry2_alter_trade_reason_exit2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exit_Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_entry3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_entry3', to='main.enter_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_entry1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_entry1', to='main.enter_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_entry2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_entry2', to='main.enter_trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_exit3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_exit3', to='main.exit_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_exit1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_exit1', to='main.exit_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_exit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_exit2', to='main.exit_trade'),
        ),
    ]
