# Generated by Django 5.1.7 on 2025-03-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_enter_trade_exit_trade_trade_reason_entry3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ManyToManyField(related_name='trade', to='main.enter_trade')),
            ],
        ),
    ]
