# Generated by Django 5.1.7 on 2025-03-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='reason_entry1',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_entry2',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_entry3',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_exit1',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_exit2',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_exit3',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_entry1',
            field=models.ManyToManyField(related_name='trades_as_entry1', to='main.enter_trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_entry2',
            field=models.ManyToManyField(blank=True, null=True, related_name='trades_as_entry2', to='main.enter_trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_entry3',
            field=models.ManyToManyField(blank=True, null=True, related_name='trades_as_entry3', to='main.enter_trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_exit1',
            field=models.ManyToManyField(related_name='trades_as_exit1', to='main.exit_trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_exit2',
            field=models.ManyToManyField(blank=True, null=True, related_name='trades_as_exit2', to='main.exit_trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='reason_exit3',
            field=models.ManyToManyField(blank=True, null=True, related_name='trades_as_exit3', to='main.exit_trade'),
        ),
    ]
