# Generated by Django 5.1.7 on 2025-03-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_trade_reason_entry1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='reason_entry2',
            field=models.ManyToManyField(blank=True, related_name='trades_as_entry2', to='main.enter_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_entry3',
            field=models.ManyToManyField(blank=True, related_name='trades_as_entry3', to='main.enter_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_exit2',
            field=models.ManyToManyField(blank=True, related_name='trades_as_exit2', to='main.exit_trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason_exit3',
            field=models.ManyToManyField(blank=True, related_name='trades_as_exit3', to='main.exit_trade'),
        ),
    ]
