# Generated by Django 5.1.7 on 2025-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_trade_reason_entry2_alter_trade_reason_entry3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='long',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='trade',
            name='loss',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='trade',
            name='short',
            field=models.BooleanField(default=None),
        ),
    ]
