# Generated by Django 5.1.7 on 2025-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_trade_long_trade_loss_trade_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(default='meme.png', upload_to='trade_pictures'),
        ),
    ]
