# Generated by Django 5.1.7 on 2025-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_trade_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(upload_to='trade_pictures'),
        ),
    ]
