# Generated by Django 5.1.7 on 2025-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_trade_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(blank=True, default=None, upload_to='trade_pictures'),
        ),
    ]
