# Generated by Django 5.1.7 on 2025-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_trade_picture1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim3', models.TimeField(auto_created=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('time2', models.TimeField(auto_now=True)),
            ],
        ),
    ]
