# Generated by Django 5.1.7 on 2025-03-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='tim3',
        ),
    ]
