# Generated by Django 5.1.7 on 2025-03-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_time_tim3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time2',
        ),
    ]
