# Generated by Django 5.1.7 on 2025-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_time_time_remove_time_time2'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(),
        ),
    ]
