# Generated by Django 5.1.7 on 2025-03-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_trade_time_alter_trade_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='time',
            new_name='entry_time',
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
