# Generated by Django 5.1.7 on 2025-03-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_time_rename_time_trade_entry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_time',
            field=models.TimeField(),
        ),
    ]
