# Generated by Django 5.1.7 on 2025-03-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_trade_trim1_alter_trade_trim2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='reason_entry1',
            new_name='reasons_entry',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='reason_exit1',
            new_name='reasons_exit',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_entry2',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_entry3',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_exit2',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reason_exit3',
        ),
    ]
