# Generated by Django 5.1.7 on 2025-03-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_reason_entry1_trade_reasons_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(blank=True, default=None, upload_to='trade_pictures/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='picture2',
            field=models.ImageField(blank=True, default=None, upload_to='trade_pictures/'),
        ),
    ]
