# Generated by Django 5.1.7 on 2025-03-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_enter_trade_user_exit_trade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enter_trade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exit_trade',
            name='user',
        ),
    ]
