# Generated by Django 5.1.7 on 2025-03-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_enter_trade_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart.png', upload_to='trade_pictures/'),
        ),
    ]
