# Generated by Django 5.1.7 on 2025-03-29 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_trade_picture1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('call', models.BooleanField()),
                ('put', models.BooleanField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('option_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit', models.BooleanField()),
                ('loss', models.BooleanField()),
                ('p_and_l', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trim1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trim2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exit_option_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('picture1', models.ImageField(blank=True, default='chart.png', upload_to='trade_pictures/')),
                ('picture2', models.ImageField(blank=True, default='chart.png', upload_to='trade_pictures/')),
                ('quantity', models.SmallIntegerField(blank=True, default=None)),
                ('reasons_entry', models.ManyToManyField(related_name='trades_as_entry2', to='main.enter_trade')),
                ('reasons_exit', models.ManyToManyField(related_name='trades_as_exit2', to='main.exit_trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
