# Generated by Django 5.1.7 on 2025-03-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_optionstrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrade',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='trade_pictures/'),
        ),
    ]
