# Generated by Django 5.1.7 on 2025-03-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_optionstrade_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart_UqV2wpr.png', null=True, upload_to='trade_pictures/'),
        ),
        migrations.AlterField(
            model_name='optionstrade',
            name='trim1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrade',
            name='trim2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
