# Generated by Django 5.1.7 on 2025-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_optionstrade_picture1_alter_optionstrade_trim1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrade',
            name='strike_price',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='optionstrade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart.png', null=True, upload_to='trade_pictures/'),
        ),
        migrations.AlterField(
            model_name='optionstrade',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
