# Generated by Django 5.1.7 on 2025-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_optionstrade_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrade',
            name='strike_price',
            field=models.BigIntegerField(default=100),
        ),
    ]
