# Generated by Django 5.1.7 on 2025-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_optionstrade_strike_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrade',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
