# Generated by Django 5.1.7 on 2025-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_optionstrade_other_notes_trade_other_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='optionstrade',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='picture2',
            field=models.ImageField(blank=True, default=None, upload_to='media/'),
        ),
    ]
