# Generated by Django 5.1.7 on 2025-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_optionstrade_strike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrade',
            name='strike_price',
            field=models.BigIntegerField(),
        ),
    ]
