# Generated by Django 5.1.7 on 2025-03-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_optionstrade_strike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrade',
            name='other_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trade',
            name='other_notes',
            field=models.TextField(default=''),
        ),
    ]
