# Generated by Django 5.1.7 on 2025-04-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_optionstrade_picture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart.png', null=True, upload_to='trading_pictures/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='picture2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='trading_pictures/'),
        ),
    ]
