# Generated by Django 5.1.7 on 2025-03-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_optionstrade_other_notes_trade_other_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrade',
            name='other_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='other_notes',
            field=models.TextField(),
        ),
    ]
