# Generated by Django 5.1.7 on 2025-04-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_trade_picture1_alter_trade_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='picture1',
            field=models.ImageField(blank=True, default='chart.png', null=True, upload_to='trade_pictures/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='picture2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='trade_pictures/'),
        ),
    ]
